package rules_fy17;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class PersAutoPolicyQuoteInqRq implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "PERSAUTOPOLICYQUOTEINQRQ_ID_GENERATOR")
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(sequenceName = "PERSAUTOPOLICYQUOTEINQRQ_ID_SEQ", name = "PERSAUTOPOLICYQUOTEINQRQ_ID_GENERATOR")
    private java.lang.Long id;

    public PersAutoPolicyQuoteInqRq() {
    }
    
    public PersAutoPolicyQuoteInqRq(java.lang.Long id) {
        this.id = id;
    }

    public java.lang.Long getId() {
        return this.id;
    }
    
    public void setId(java.lang.Long id) {
        this.id = id;
    }

}